--Kavos
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("NRS Cheats", "Ocean")


--Main
local MainTab = Window:NewTab("Skins")
local MainSection = MainTab:NewSection("Change Troup Skins")
local BTab = Window:NewTab("Blatant")
local BSection = BTab:NewSection("Blatant Cheats")
BSection:NewLabel("WARNING USE ALTS THIS CAN GET YOU BANNED")
local CountryTab = Window:NewTab("Country")
local CSection = CountryTab:NewSection("Country")
CSection:NewLabel("Can get you banned if you arent careful")
 MainSection:NewButton("use skin UPA", "e", function()
    local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "UPA Skin"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)

end)
 MainSection:NewButton("use skin Santa", "e", function()
    local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "Santa"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)

end)
 MainSection:NewButton("use skin Germany", "e", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "German Skin"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)


end)

 MainSection:NewButton("use skin Astolfo", "e", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "Astolfo skin"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)


end)
MainSection:NewButton("use skin Normal cat", "e", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "Catgirl Maid"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)


end)
MainSection:NewButton("use skin pink cat", "e", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "Catgirl Maid (Pink)"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)


end)
MainSection:NewButton("use skin Plague", "e", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "Plague Doctor"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)


end)
MainSection:NewButton("use skin Hog Rider", "e", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "Hog Rider Skin"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)


end)
MainSection:NewButton("use skin Napoleon", "e", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "French Skin"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)


end)
MainSection:NewButton("use skin Dababy", "e", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "Dababy skin"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)


end)
MainSection:NewButton("use skin Troll", "e", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "TrollFace"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)


end)
MainSection:NewButton("use skin Amogus", "e", function()
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	[1] = "SkinChanged", 
	[2] = "Sussy Skin"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)


end)
CSection:NewTextBox("Play as (TAG)", "Selects Specific Country", function(txt)
	local A_1 = 
{
	[1] = "CountrySelected", 
	[2] = txt
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)
end)
BSection:NewTextBox("Disband Alliance", "disbands an Alliance", function(txt)
	
    local e = txt
    local A_1 = 
{
	[1] = "FactionDisband", 
	[2] = game:GetService("Workspace").Factions[e]
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)
end)


BSection:NewTextBox("Faction1(your country)", "this is ez stuff", function(txt)
    
    local e = txt
    local A_1 = 
{
	[1] = "FactionCreate", 
	[2] = game:GetService("Workspace").Countries[e], 
	[3] = "e"
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)

end)
BSection:NewTextBox("Faction (for Germany)", "e", function(txt)
    local A_1 = 
{
	[1] = "FactionAccepted", 
	[2] = game:GetService("Workspace").Countries.GER, 
	[3] = txt
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)

end)
BSection:NewTextBox("Faction (for France)", "e", function(txt)
    local A_1 = 
{
	[1] = "FactionAccepted", 
	[2] = game:GetService("Workspace").Countries.FRA, 
	[3] = txt
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)

end)
BSection:NewTextBox("Faction (for Uruguay)", "e", function(txt)
    local A_1 = 
{
	[1] = "FactionAccepted", 
	[2] = game:GetService("Workspace").Countries.URU, 
	[3] = txt
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)

end)
BSection:NewTextBox("Faction (for Siam)", "e", function(txt)
    local A_1 = 
{
	[1] = "FactionAccepted", 
	[2] = game:GetService("Workspace").Countries.THA, 
	[3] = txt
}
local Event = game:GetService("ReplicatedStorage").Event
Event:FireServer(A_1)

end)

print("enjoy yall :)")